### PR TITLE
Optional callback for Stale records

### PR DESCRIPTION
**Pull request by lmangani**
This one-liner proposal for comments and discussion implements an optional cb() function fired when GC contains stale records. Not sure if interesting, acceptable or achievable in a better way, but worth a shot - Thanks for your awesome work!

### CODE REVIEW

**Comment by mafintosh** [comment]
cool! i think we should name this something over than `cb` though. perhaps `ongc` or `onstale` ?

**Comment by lmangani** [comment]
Excellent point - option renamed to `onStale` + README entry - please squash if accepted :)

**Comment by lmangani** [comment]
Just noticed the other options use capitalization - shall I change to `onStale` for consistency and squash it all later?

**Comment by mafintosh** [comment]
Out in 1.1.0 :) Tweaked it a bit so you can use `opts.onstale` as well as `opts.onStale`

**Pull request merged**
